// @hostname = https://phonebook-jrip.onrender.com
GET {{hostname}}/info
###
GET {{hostname}}/api/persons
###
# @prompt id
GET {{hostname}}/api/persons/{{id}}
###
# @prompt id
DELETE {{hostname}}/api/persons/{{id}}
###
POST {{hostname}}/api/persons
content-Type: application/json

{
  "name": "John Doe",
  "number": "12-12-123456"
}
###
POST {{hostname}}/api/persons
content-Type: application/json

{
  "name": "John Doe"
}
###
POST {{hostname}}/api/persons
content-Type: application/json

{
  "number": "12-12-123456"
}
