@baseUrl = http://localhost:3001
GET {{baseUrl}}/info
###
GET {{baseUrl}}/api/persons
###
GET {{baseUrl}}/api/persons/1
###
DELETE {{baseUrl}}/api/persons/1
###
POST {{baseUrl}}/api/persons
content-Type: application/json

{
  "name": "John Doe",
  "number": "12-12-123456"
}
###
POST {{baseUrl}}/api/persons
content-Type: application/json

{
  "name": "John Doe"
}
###
POST {{baseUrl}}/api/persons
content-Type: application/json

{
  "number": "12-12-123456"
}
